Added blank login page that returns jwt
RAF-SI-2023/Banka-1-Frontend pull request #12
Opened 2024-03-09 12:52 UTC by marequest

2024-03-11 23:51 UTC, RadenkovicZarko commented on src/app/login-page/login-page.component.ts
> +
Ukoliko ne moze da se uloguje, ne treba da baca error na konzoli vec da izbaci pop-up.

2024-03-11 23:53 UTC, RadenkovicZarko commented on src/app/login-page/login-page.component.html
> +    <a href="/login">Forgot Password?</a>
Lepa zamisao, ali nemamo tu funkcionalnost jos uvek. Zakomentarisi ovo. Ne smemo da imamo dugme koje nista ne radi.

2024-03-11 23:54 UTC, RadenkovicZarko commented on src/app/auth.service.ts
> +    // );
Ovo ne treba da bude komentarisano, potrebno je da bude kod funkcionalan kada se pushuje, kao da imamo api.

2024-03-11 23:56 UTC, RadenkovicZarko commented on src/app/auth.service.spec.ts
Stavljaj ovo u folder, svi servisi idu u service folder

2024-03-11 23:56 UTC, RadenkovicZarko commented on src/app/auth.service.ts
> +    // );
Stavljaj i ovaj servis u folder service

2024-03-11 23:56 UTC, RadenkovicZarko commented on src/app/popup.service.spec.ts
u folder service

2024-03-11 23:57 UTC, RadenkovicZarko commented on src/app/popup.service.ts
u folder service :)

2024-03-12 00:08 UTC, RadenkovicZarko requested changes
Potrebne izmene, ali je dobro i lepo

2024-03-12 19:23 UTC, marequest reviewed
Nisam siguran kolko sam pravilno resio konflikte pri pull upstream tako da bacite pogled, 
Validator u loginu nisam koristio, ako treba to da uradim javite.

2024-03-12 20:05 UTC, RadenkovicZarko approved these changes

2024-03-12 20:06 UTC, merged